### ISSUE TITLE
Jobs

### ISSUE THREAD

**Issue by pj00** [CCOMIT/createstudy-irbaudit#2]
#### generateStudyDetailsReport
- [x] Errors out (but still works sporadically) when running against HC-SQL7DEV (see stack trace below)

#### updateAllStudies
- [x] Check for last successful run and use that date for `sinceDate` 
- [x] Does sendMail work?

### New Jobs
- [x] Need job that looks for studies that Epic isn't accepting and creates report

**Comment by pj00** [comment]
```
org.springframework.core.task.TaskRejectedException: Executor [java.util.concurrent.ThreadPoolExecutor@3f8ac095[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]] did not accept task: org.springframework.aop.interceptor.AsyncExecutionInterceptor$$Lambda$478/607659782@5a6fd075
      at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.submit(ThreadPoolTaskExecutor.java:344) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
      at org.springframework.aop.interceptor.AsyncExecutionAspectSupport.doSubmit(AsyncExecutionAspectSupport.java:290) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
      at org.springframework.aop.interceptor.AsyncExecutionInterceptor.invoke(AsyncExecutionInterceptor.java:129) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
      at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
      at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) ~[spring-aop-5.1.6.RELEASE.jar:5.1.6.RELEASE]
      at edu.uiowa.icts.createstudy.jobs.GenerateIrbReports$$EnhancerBySpringCGLIB$$e36e2c55.generateStudyDetailsReport(<generated>) ~[classes/:na]
      at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212-1-ojdkbuild]
      at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212-1-ojdkbuild]
      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212-1-ojdkbuild]
      at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212-1-ojdkbuild]
      at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
      at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
      at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_212-1-ojdkbuild]
      at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_212-1-ojdkbuild]
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_212-1-ojdkbuild]
      at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_212-1-ojdkbuild]
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_212-1-ojdkbuild]
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_212-1-ojdkbuild]
      at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212-1-ojdkbuild]
Caused by: java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@37d7c971 rejected from java.util.concurrent.ThreadPoolExecutor@3f8ac095[Running, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
      at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[na:1.8.0_212-1-ojdkbuild]
      at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) [na:1.8.0_212-1-ojdkbuild]
      at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1379) [na:1.8.0_212-1-ojdkbuild]
      at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134) ~[na:1.8.0_212-1-ojdkbuild]
      at org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor.submit(ThreadPoolTaskExecutor.java:341) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
      ... 19 common frames omitted

```
